version: '3.4'

services:
    api.gateway:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConsulConfig__Address: http://c_consul:8500
            ConsulConfig__ServiceAddress: http://localhost:5010
        ports:
        - "5010:80"
        networks:
        - net_backend
        restart: no
        mem_limit: 1g
  
    commerce.service:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConsulConfig__Address: http://c_consul:8500
            ConsulConfig__ServiceAddress: http://localhost:5000
        ports:
        - "5000:80"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_sqlserver
        - s_rabbitmq
        - api.gateway
        - s_redis
        - s_consul
        mem_limit: 1g

    stock.service:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConsulConfig__Address: http://c_consul:8500
            ConsulConfig__ServiceAddress: http://localhost:5001
        ports:
        - "5001:80"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_sqlserver
        - s_rabbitmq
        - s_consul
        mem_limit: 1g

    email.service:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConsulConfig__Address: http://c_consul:8500
            ConsulConfig__ServiceAddress: http://localhost:5002
        ports:
        - "5002:80"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_sqlserver
        - s_rabbitmq
        - s_consul
        mem_limit: 1g

    identity.service:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConsulConfig__Address: http://c_consul:8500
            ConsulConfig__ServiceAddress: http://localhost:5003
        ports:
        - "5003:80"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_sqlserver
        - s_rabbitmq
        - api.gateway
        - s_consul
        mem_limit: 1g

    invoice.service:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConsulConfig__Address: http://c_consul:8500
            ConsulConfig__ServiceAddress: http://localhost:5004
        ports:
        - "5004:80"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_mongo
        - s_consul
        - s_rabbitmq
        mem_limit: 1g

    payment.service:
        environment:
            ASPNETCORE_ENVIRONMENT: Development
            ConsulConfig__Address: http://c_consul:8500
            ConsulConfig__ServiceAddress: http://localhost:5005
        ports:
        - "5005:80"
        networks:
        - net_backend
        restart: no
        depends_on:
        - s_sqlserver
        - s_rabbitmq
        - s_consul
        mem_limit: 1g

    s_sqlserver:
        user: root
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: Test123!_
        ports:
        - "1433:1433"
        volumes:
        - sqlserver_data:/var/opt/mssql/data
        - sqlserver_log:/var/opt/mssql/log
        networks:
        - net_backend
        mem_limit: 2g
    
    s_rabbitmq:
        ports:
        - 5672:5672
        - 15672:15672
        volumes:
        - rabbitmq:/var/lib/rabbitmq
        networks:
        - net_backend
        restart: on-failure
        environment:
            RABBITMQ_HOST: localhost
            RABBITMQ_DEFAULT_USER: guest
            RABBITMQ_DEFAULT_PASS: guest

    s_mongo:
        ports:
        - 27017:27017
        restart: always
        networks:
        - net_backend

    s_redis:
        ports:
        - 6379:6379
        volumes:
        - /opt/app_data/redis/:/data
        networks:
        - net_backend

    s_consul:
        ports:
        - 8500:8500
        - 8600:8600/tcp
        - 8600:8600/udp
        networks:
        - net_backend

networks:
    net_backend:
        driver: bridge

volumes:
    rabbitmq:
    sqlserver_data:
    sqlserver_log: