version: '3.4'

services:
  web.api:
    image: ${DOCKER_REGISTRY-}cliccowebapi
    build:
      context: .
      dockerfile: Presentation/Clicco.WebAPI/Dockerfile

  payment.service.api:
    image: ${DOCKER_REGISTRY-}cliccopaymentserviceapi
    build:
      context: .
      dockerfile: Presentation/Services/Clicco.PaymentServiceAPI/Dockerfile


  invoice.service.api:
    image: ${DOCKER_REGISTRY-}cliccoinvoiceserviceapi
    build:
      context: .
      dockerfile: Presentation/Services/Clicco.InvoiceServiceAPI/Dockerfile


  email.service.api:
    image: ${DOCKER_REGISTRY-}cliccoemailserviceapi
    build:
      context: .
      dockerfile: Presentation/Services/Clicco.EmailServiceAPI/Dockerfile


  auth.service.api:
    image: ${DOCKER_REGISTRY-}cliccoauthserviceapi
    build:
      context: .
      dockerfile: Presentation/Services/Clicco.AuthAPI/Dockerfile


  web.api.gateway:
    image: ${DOCKER_REGISTRY-}cliccowebapigateway
    build:
      context: .
      dockerfile: Presentation/ApiGateways/Clicco.Web.ApiGateway/Dockerfile


  test.project:
    image: ${DOCKER_REGISTRY-}cliccotests
    build:
      context: .
      dockerfile: Tests/WebApi/Clicco.Tests/Dockerfile

  s_redis:
    container_name: c_redis
    image: redis

  s_rabbitmq:
    container_name: c_rabbitmq
    image: rabbitmq:3-management

  s_sqlserver:
    container_name: c_sqlserver
    image: mcr.microsoft.com/mssql/server:2019-latest

  s_mongo:
    container_name: c_mongo
    image: mongo

networks:
    net_apiqateway:
        driver: bridge
        external: true
    net_backendservices :
        driver: bridge
        external: true
