version: '3.4'
services:
  
  web.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development 
    ports:
      - "5000:5000"
    networks:
      - net_backendservices
      - net_apigateway
    restart: always
    depends_on:
      - web.api.gateway
      - s_rabbitmq
      - s_redis
      - s_sqlserver
    mem_limit: 1g
  
  web.api.gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5010:5010"
    restart: always
    networks:
      - net_apigateway
    mem_limit: 512m
  
  email.service.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5002:5002"
    networks:
      - net_backendservices
      - net_apigateway
    restart: always
    depends_on:
      - web.api.gateway
      - s_rabbitmq
      - s_sqlserver
    labels:
        Names: email.service.api
    mem_limit: 512m
  
  invoice.service.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "MongoDbSettings:ConnectionString=mongodb://catalogdb:27017"
    ports:
      - "5004:5004"
    restart: always
    networks:
      - net_backendservices
      - net_apigateway
    depends_on:
      - web.api.gateway
      - s_rabbitmq
      - s_mongo
    mem_limit: 512m
  
  payment.service.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:5003"
    restart: always
    networks:
      - net_apigateway
      - net_backendservices
    depends_on:
      - web.api.gateway
      - s_rabbitmq
    mem_limit: 512m
  
  auth.service.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:5001"
    networks:
      - net_backendservices
      - net_apigateway
    depends_on:
      - web.api.gateway
      - s_rabbitmq
      - s_sqlserver
    mem_limit: 512m
    
  test.project:
   environment:
    - ASPNETCORE_ENVIRONMENT=Development
   mem_limit: 1g
  
  s_sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql2019
    restart: always
    environment:
      SA_PASSWORD: "sqlsa"
      ACCEPT_EULA: "Y" 
    ports:
      - "1433:1433"
    labels:
      NAME: "s_sqlserver"
    volumes:
      - ./mssql_volume:/var/opt/mssql
    networks:
      - net_backendservices
    mem_limit: 2g
    
  s_rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - net_backendservices
      - net_apigateway
    labels:
     Names: s_rabbitmq
    mem_limit: 1g
  
  s_redis:
    ports:
      - 6379:6379
    volumes:
      - /opt/app_data/redis/:/data
    networks:
      - net_backendservices
      - net_apigateway
    mem_limit: 1g
  
  s_mongo:
    image: mongo
    ports:
      - "27017:27017"
    labels:
      Names: s_mongo
    mem_limit: 1g

networks:
    net_apigateway:
        driver: bridge
        #external: true
    net_backendservices :
        driver: bridge
        #external: true

volumes:
    rabbitmq:
    sqlserver_data:
    sqlserver_log: