version: '3.4'

services:
    api.gateway:
        image: ${DOCKER_REGISTRY-}apigateway
        build:
            context: .
            dockerfile: src/API.Gateway/Dockerfile

    commerce.service:
        image: ${DOCKER_REGISTRY-}commerceserviceapi
        build:
            context: .
            dockerfile: src/CommerceService/Presentation/Dockerfile

    email.service:
        image: ${DOCKER_REGISTRY-}emailservice
        build:
            context: .
            dockerfile: src/EmailService/Dockerfile
    
    identity.service:
        image: ${DOCKER_REGISTRY-}identityservice
        build:
            context: .
            dockerfile: src/IdentityService/Dockerfile
    
    invoice.service:
        image: ${DOCKER_REGISTRY-}invoiceservice
        build:
            context: .
            dockerfile: src/InvoiceService/Dockerfile
    
    payment.service:
        image: ${DOCKER_REGISTRY-}paymentservice
        build:
            context: .
            dockerfile: src/PaymentService/Dockerfile
    
    stock.service:
        image: ${DOCKER_REGISTRY-}stockservice
        build:
            context: .
            dockerfile: src/StockService/StockWorkerService/Dockerfile

    s_sqlserver:
        container_name: c_sqlserver
        image: mcr.microsoft.com/mssql/server:2019-latest

    s_rabbitmq:
        container_name: c_rabbitmq
        image: rabbitmq:3-management

    s_mongo:
        container_name: c_mongo
        image: mongo
  
    s_redis:
        container_name: c_redis
        image: redis:alpine

    s_consul:
        container_name: c_consul
        image: consul:1.15.4